# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import ecflow_client_pb2 as ecflow__client__pb2


class EcflowClientServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CollectStatusRecords = channel.unary_unary(
        '/ecflow_client.EcflowClientService/CollectStatusRecords',
        request_serializer=ecflow__client__pb2.StatusRequest.SerializeToString,
        response_deserializer=ecflow__client__pb2.StatusRecordsResponse.FromString,
        )
    self.CollectStatus = channel.unary_unary(
        '/ecflow_client.EcflowClientService/CollectStatus',
        request_serializer=ecflow__client__pb2.StatusRequest.SerializeToString,
        response_deserializer=ecflow__client__pb2.StatusResponse.FromString,
        )
    self.CollectNode = channel.unary_unary(
        '/ecflow_client.EcflowClientService/CollectNode',
        request_serializer=ecflow__client__pb2.NodeRequest.SerializeToString,
        response_deserializer=ecflow__client__pb2.NodeResponse.FromString,
        )


class EcflowClientServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CollectStatusRecords(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CollectNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EcflowClientServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CollectStatusRecords': grpc.unary_unary_rpc_method_handler(
          servicer.CollectStatusRecords,
          request_deserializer=ecflow__client__pb2.StatusRequest.FromString,
          response_serializer=ecflow__client__pb2.StatusRecordsResponse.SerializeToString,
      ),
      'CollectStatus': grpc.unary_unary_rpc_method_handler(
          servicer.CollectStatus,
          request_deserializer=ecflow__client__pb2.StatusRequest.FromString,
          response_serializer=ecflow__client__pb2.StatusResponse.SerializeToString,
      ),
      'CollectNode': grpc.unary_unary_rpc_method_handler(
          servicer.CollectNode,
          request_deserializer=ecflow__client__pb2.NodeRequest.FromString,
          response_serializer=ecflow__client__pb2.NodeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ecflow_client.EcflowClientService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
